<?php
return array(
	//'配置项'=>'配置值'
	'DB_PREFIX'=>'tp_',
	//配置模糊查询
	'DB_LIKE_FIELDS'=>'title|content',
	//连接的数据库名称端口
	//'DB_DSN'=>'mysql://root:@localhost:3306/classmanage',
	'DB_HOST'=>'localhost',
	'DB_NAME'=>'classmanage',
	'DB_USER'=>'root',
	'DB_PWD'=>'root',
	'DB_PORT'=>'3306',
	//修改URL的分隔符
	'URL_PATHINFO_DEPR'=>'/',
	//开启页面Trace
	'SHOW_PAGE_TRACE'=>true,
	 //修改左定界符
	'TMPL_L_DELIM'=>'<{',
	 //修改右定界符
	'TMPL_R_DELIM'=>'}>',
);
?>